name: checkout workflow
on: push
jobs:
    my-first-job:
     runs-on: ubuntu-latest
     steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: List and Read files
          run: |
           echo "List all files"
           ls -ltr
        - name: use third party library
          run: cowsay -f dragon "run for cover its a dragon" >> dragon.txt
