name: my-first-workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
         - name: my first command
           run: echo "My first command:"
         - name: list all files and directories
           run: ls -la

        
