name: checkout workflow
on: push
jobs:
    my-first-job:
     runs-on: ubuntu-latest
     steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: list all files in current directory
          run: echo "list all files in current directory"
        - name: linux command
          run: ls -la

