name: generate ADSCII Artwork

on: push

jobs: 
    ascii-work:
     runs-on: ubuntu-latest
     steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: run shell script
          run: |
            chmod +x script.sh
            sh script.sh