name: generate ADSCII Artwork

on: push

jobs: 
    build_job:
     needs: test_job
     runs-on: ubuntu-latest
     steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: run shell script
          run: |
            chmod +x script.sh
            sh script.sh
    test_job: 
      runs-on: ubuntu-latest
      steps:
        - name: check the script file
          run: ls
        