name: second-workflow

on: push

jobs:
    second-job:
        runs-on: ubuntu-latest
        steps:
          - name: my second step
            run: echo "my second step"
          - name: second linux command
            run: ls
