name: secrets at job level
on: push
jobs:
    docker:
     env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: vamsi1997docker
            DOCKER_PASSWORD: Ismav1234#
            IMAGE_NAME: github-actions-nginx
     runs-on: ubuntu-latest
     steps:
        - name: Docker Build
          run: echo "docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest"

        - name: Docker login
          run: echo "docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}"

        - name: docker publish
          run: echo "docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest"
          
    deploy_job:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: docker run
              run: echo "docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest"
             

